---
- name : Validate setenv.sh script
  become: yes
  command: "bash -n {{ staging_dir }}/setenv.sh"
  register: validate_setenv_script  
  failed_when: validate_setenv_script.rc != 0

- name: policy check for setenv.sh script
  become: yes
  shell: >
    grep -Eq '^export[[:space:]]+CATALINA_OPTS="-(Xms|Xmx|XX:).*"$' 
    "{{ staging_dir }}/setenv.sh"
  register: catalina_opts_overwrite_detect
  changed_when: false
  failed_when: catalina_opts_overwrite_detect.rc == 0

- name: Show Validation Results
  debug:
    msg: 
      - "Validation of setenv.sh script passed successfully."
      - "CATALINA_OPTS overwrite check passed successfully."