---
- name: startup tomcat instance
  become: true
  become_user: parallels
  shell: "{{ tomcat.catalina_home }}/bin/startup.sh"
  environment:
    CATALINA_HOME: "{{ tomcat.catalina_home }}"
    CATALINA_BASE: "{{ tomcat.catalina_base }}"
  register: startup_result
  ignore_errors: true
