---
- name: Ensure staging directory exists
  ansible.builtin.file:
    path: "{{ staging_dir }}"
    state: directory
    owner: "{{ jboss.install_owner }}"
    group: "{{ jboss.install_group }}"
    mode: "0755"

- name: Ensure root instance directory exists
  ansible.builtin.file:
    path: "{{ jboss.instance_root }}"
    state: directory
    owner: "{{ jboss.install_owner }}"
    group: "{{ jboss.install_group }}"
    mode: "0755"

- name: Create directory tree for new JBoss instances
  ansible.builtin.file:
    path: >-
      {{ jboss.instance_root }}/{{ item.0 }}{{ '' if item.1 == '' else '/' ~ item.1 }}
    state: directory
    owner: "{{ jboss.install_owner }}"
    group: "{{ jboss.install_group }}"
    mode: "0755"
  loop: "{{ missing_instance_names | product(jboss.instance_subdirs) | list }}"
  when: missing_instance_names | length > 0
