---
- name: shutdown tomcat instance
  hosts: Tomcat
  connection: local
  become: yes
  gather_facts: no

  vars_files:
    - vars/main.yml
  
  roles:
    - create_setenv_script
    - validate_setenv_script
    - create_server_xml
    - validate_server_xml
    - copy_config_files
    - shutdown
    - startup  